#!/bin/bash
#define the filename to use as output
motd="motd"
# Collect useful information about your system
# $USER is automatically defined
HOSTNAME=`uname -n`
KERNEL=`uname -r`
CPU=`uname -p`
ARCH=`uname -m`
# The different colours as variables
W="\033[01;37m"
B="\033[01;34m"
R="\033[01;31m" 
X="\033[00;37m"
clear > $motd # to clear the screen when showing up
echo  "$R#=============================================================================#" >> $motd
echo  "	$W Welcome $B $USER $W to $B $HOSTNAME                " >> $motd
echo  "	$R ARCH   $W= $ARCH                                   " >> $motd
echo  "	$R KERNEL $W= $KERNEL                                 " >> $motd
echo  "	$R CPU    $W= $CPU                                    " >> $motd
echo  "$R#=============================================================================#" >> $motd
echo  "$X" >> $motd
